/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrgentRouteImport } from './routes/urgent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CautaRouteImport } from './routes/cauta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SedintaLessonIdRouteImport } from './routes/sedinta.$lessonId'
import { Route as RezervareTutorIdRouteImport } from './routes/rezervare.$tutorId'
import { Route as ProfesorTutorIdRouteImport } from './routes/profesor.$tutorId'
import { Route as LectieLessonIdRouteImport } from './routes/lectie.$lessonId'

const UrgentRoute = UrgentRouteImport.update({
  id: '/urgent',
  path: '/urgent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CautaRoute = CautaRouteImport.update({
  id: '/cauta',
  path: '/cauta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SedintaLessonIdRoute = SedintaLessonIdRouteImport.update({
  id: '/sedinta/$lessonId',
  path: '/sedinta/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervareTutorIdRoute = RezervareTutorIdRouteImport.update({
  id: '/rezervare/$tutorId',
  path: '/rezervare/$tutorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesorTutorIdRoute = ProfesorTutorIdRouteImport.update({
  id: '/profesor/$tutorId',
  path: '/profesor/$tutorId',
  getParentRoute: () => rootRouteImport,
} as any)
const LectieLessonIdRoute = LectieLessonIdRouteImport.update({
  id: '/lectie/$lessonId',
  path: '/lectie/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cauta': typeof CautaRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/urgent': typeof UrgentRoute
  '/lectie/$lessonId': typeof LectieLessonIdRoute
  '/profesor/$tutorId': typeof ProfesorTutorIdRoute
  '/rezervare/$tutorId': typeof RezervareTutorIdRoute
  '/sedinta/$lessonId': typeof SedintaLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cauta': typeof CautaRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/urgent': typeof UrgentRoute
  '/lectie/$lessonId': typeof LectieLessonIdRoute
  '/profesor/$tutorId': typeof ProfesorTutorIdRoute
  '/rezervare/$tutorId': typeof RezervareTutorIdRoute
  '/sedinta/$lessonId': typeof SedintaLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cauta': typeof CautaRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/urgent': typeof UrgentRoute
  '/lectie/$lessonId': typeof LectieLessonIdRoute
  '/profesor/$tutorId': typeof ProfesorTutorIdRoute
  '/rezervare/$tutorId': typeof RezervareTutorIdRoute
  '/sedinta/$lessonId': typeof SedintaLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cauta'
    | '/dashboard'
    | '/onboarding'
    | '/urgent'
    | '/lectie/$lessonId'
    | '/profesor/$tutorId'
    | '/rezervare/$tutorId'
    | '/sedinta/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cauta'
    | '/dashboard'
    | '/onboarding'
    | '/urgent'
    | '/lectie/$lessonId'
    | '/profesor/$tutorId'
    | '/rezervare/$tutorId'
    | '/sedinta/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cauta'
    | '/dashboard'
    | '/onboarding'
    | '/urgent'
    | '/lectie/$lessonId'
    | '/profesor/$tutorId'
    | '/rezervare/$tutorId'
    | '/sedinta/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CautaRoute: typeof CautaRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  UrgentRoute: typeof UrgentRoute
  LectieLessonIdRoute: typeof LectieLessonIdRoute
  ProfesorTutorIdRoute: typeof ProfesorTutorIdRoute
  RezervareTutorIdRoute: typeof RezervareTutorIdRoute
  SedintaLessonIdRoute: typeof SedintaLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urgent': {
      id: '/urgent'
      path: '/urgent'
      fullPath: '/urgent'
      preLoaderRoute: typeof UrgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cauta': {
      id: '/cauta'
      path: '/cauta'
      fullPath: '/cauta'
      preLoaderRoute: typeof CautaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedinta/$lessonId': {
      id: '/sedinta/$lessonId'
      path: '/sedinta/$lessonId'
      fullPath: '/sedinta/$lessonId'
      preLoaderRoute: typeof SedintaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervare/$tutorId': {
      id: '/rezervare/$tutorId'
      path: '/rezervare/$tutorId'
      fullPath: '/rezervare/$tutorId'
      preLoaderRoute: typeof RezervareTutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesor/$tutorId': {
      id: '/profesor/$tutorId'
      path: '/profesor/$tutorId'
      fullPath: '/profesor/$tutorId'
      preLoaderRoute: typeof ProfesorTutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectie/$lessonId': {
      id: '/lectie/$lessonId'
      path: '/lectie/$lessonId'
      fullPath: '/lectie/$lessonId'
      preLoaderRoute: typeof LectieLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CautaRoute: CautaRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  UrgentRoute: UrgentRoute,
  LectieLessonIdRoute: LectieLessonIdRoute,
  ProfesorTutorIdRoute: ProfesorTutorIdRoute,
  RezervareTutorIdRoute: RezervareTutorIdRoute,
  SedintaLessonIdRoute: SedintaLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
